### PR TITLE
Fix for never ending recursion

### PR DESCRIPTION
**Pull request by ahwayakchih**
If some other field also calls `prepareTableValue()` on other fields, it can quickly start recursion between SubsectionManager field and other field. Never ending loop. This fixes the problem by adding local, static cache for prepared values.

### CODE REVIEW

**Comment by brendo** [comment]
Sorry, nonsense comment, but I like the recursion in your comment names, very fitting :D

**Comment by ahwayakchih** [comment]
Haha, and totally by accident :).

**Comment by nilshoerrmann** [comment]
Really?

**Comment by nilshoerrmann** [comment]
Really?

**Comment by nilshoerrmann** [comment]
Really?

**Comment by ahwayakchih** [comment]
:D

**Pull request merged**
