### PR TITLE
Breadcrumb mode exclusions

### PR DESCRIPTION
**Pull request by henrysingleton**
As per this forum post: http://symphony-cms.com/discuss/thread/83270/2/#position-23

This adds the Breadcrumb field element modes to the mode exclusion list. Also changes exclusion list to array for easier additions in future.

### CODE REVIEW

**Comment by nilshoerrmann** [comment]
Hey Henry, thanks for that. Maybe we can make this more general. Could you please try if this works for you as well?

```
    /**
     * Parse data source and extract subsection fields
     *
     * @param DataSource $datasource
     *  The data source class to parse
     */
    private function __parseSubsectionFields($fields, $context, $datasource = null) {

        // Get source
        $section = 0;
        if(is_numeric($datasource)) {
            $section = $datasource;
        }
        elseif(is_object($datasource)) {
            if(method_exists($datasource, 'getSource')) {
                $section = intval($datasource->getSource());
            }
        }

        // Fetch Subsection fields
        $subsection_fields = Symphony::Database()->fetchCol('element_name', "
            SELECT element_name 
            FROM `tbl_fields` 
            WHERE (`type` = 'subsectionmanager' 
            OR `type` = 'subsectiontabs')
            AND `parent_section`= {$section}
        ");

        // Parse included elements
        if(!empty($fields)) {
            foreach($fields as $index => $included) {
                list($subsection, $field, $remainder) = explode(': ', $included, 3);

                // Fetch fields
                if(in_array($subsection, $subsection_fields) && !empty($field)) {

                    // Get field id and mode
                    if(!isset(self::$storage['fields'][$context]) || self::$updateCache == true) {
                        if($remainder == 'formatted' || $remainder == 'unformatted' || $reminder == 'increment' || empty($remainder)) {
                            $this->__fetchFields($section, $context, $subsection, $field, $remainder);
                        }
                        else {
                            $subsection_id = $this->__fetchFields($section, $context, $subsection, $field, "{$context}/{$subsection}");
                            $this->__parseSubsectionFields(array($field . ': ' . $remainder), "{$context}/{$subsection}", $subsection_id);
                        }

                        // Make sure fields will be stored
                        self::$updateCache = true;
                    }

                    // Set a single field call for subsection fields
                    if(is_object($datasource)) {
                        unset($datasource->dsParamINCLUDEDELEMENTS[$index]);

                        $storage = $subsection . ': ' . $context;
                        if(!in_array($storage, $datasource->dsParamINCLUDEDELEMENTS)) {
                            $datasource->dsParamINCLUDEDELEMENTS[$index] = $storage;
                        }
                    }
                }
            }
        }
    }
```

Note to self: If it works, the subsection field names have to be fetched and stored once and the second check for `formatted`/`unformatted`/`increment` has to be replaced as well.

**Comment by nilshoerrmann** [comment]
@henrysingleton, have you found the time to look at the proposed change?

**Comment by henrysingleton** [comment]
Sorry mate, got smashed with work the past few days. I'll take a look tomorrow.

**Comment by lnikkila** [comment]
I ran into this problem too and it looks like the proposed fix above works fine.

**Comment by nilshoerrmann** [comment]
Thanks for your feedback!

**Pull request closed without merging**
