### PR TITLE
First step to fixing nested SubsectionManager fields.

### PR DESCRIPTION
**Pull request by ahwayakchih**
Please, do not pull this one yet.

I need Your input here. What is these lines are about (https://github.com/nilshoerrmann/subsectionmanager/blob/2.x/extension.driver.php#L250)?

```
                        $storage = $subsection . ': ' . $context;
                        if(!in_array($storage, $datasource->dsParamINCLUDEDELEMENTS)) {
                            $datasource->dsParamINCLUDEDELEMENTS[$index] = $storage;
                        }
```

I know it generates "ID" for cache, and then adds it to data source, but i am not sure how to fix it for nested fields. When called inside recursion, this will not have access to "real" data source. Should i change that? Or is it not needed at all (for sub-subsectionmanager fields)?

### CODE REVIEW

**Comment by nilshoerrmann** [comment]
This is the general concept:
- The array of included elements is reduced to include only one reference per Subsection Manager field. This is needed to make sure that `appendFormattedElement()` is only called once _per Subsection Manager field_ and not once _per selected subsection field_ (in the latter case you'd see the Subsection Manager's XML tree added as often as we have selected subsection fields).
- The extension driver uses the quoted lines to store two things: the Subsection Manager's **field name** and the **data source root element** which will be passed as mode (`$context`) to `appendFormattedElement()`.
- Before that – before reducing the array stored in the data source – the extension driver [fetches the all selected subsection fields ids](https://github.com/nilshoerrmann/subsectionmanager/blob/2.x/extension.driver.php#L287) and stores them in `self::storage['fields'][$context]`, where `$context` represents the name of the data source root element again.
- Normally `appendFormattedElement()` doesn't know about the data source it is called from, but because we pass the root element as mode/context we are able to restore all included fields form 
  `extension_subsectionmanager::$storage['fields'][$context]`. So the Subsection Manager [loops](https://github.com/nilshoerrmann/subsectionmanager/blob/2.x/fields/field.subsectionmanager.php#L702) through all the stored fields [recursively](https://github.com/nilshoerrmann/subsectionmanager/blob/2.x/fields/field.subsectionmanager.php#L713) to add them to the XML tree.

But this is not all the magic: The extension driver is also pre-fetching all subsection entries and stores them inside `self::storage['entries']`. This is done for performance reasons because the data source already knows all entry ids. So `appendFormattedElements()` just fetches the entry object from the storage and only calls `entryManager` directly in case and entry has – for some reason – not been pre-fetched (e. g. for custom data sources not providing `$datasource->dsParamINCLUDEDELEMENTS`).

I hope this made a few things clearer. It's working on my side but I've got the slight feeling that your site is way more complicated then ours so if fields are not added recursively on your install we either have a merging conflict or a logic bug.

If I confused you with my explaination, please ask questions. This extension is a complicated beast.

**Comment by ahwayakchih** [comment]
> If I confused you with my explaination, please ask questions.

No, it is a very clean explanation, thanks :). I "discovered" parts of those things yesterday, but your explanation clarifies a lot for me.

> This extension is a complicated beast.

Yep :).

There is another problem i found with this:

> The extension driver uses the quoted lines to store two things: the Subsection Manager's field name and the data source root element which will be passed as mode ($context) to appendFormattedElement().

If two fields in two sections have the same name, one will overwrite another. For example, there are 3 sections: News, Reviews and Objects. News and Reviews have "Objects" SSM fields. News has also "Linked Reviews" SSM field, and Reviews has "Linked News" SSM field. So we get something like this in Data Source editor that selects entries from Reviews section:

```
Title
Objects : Name
Objects : Type
Linked news : Title
Linked news : Objects : Name
Linked news : Objects : Type
```

When i want to select objects directly "connected" to Review and objects from linked news, it looks like SSM will be able to select just one of them (because cached settings for second one will overwrite cached settings for first one).

Maybe context should contain "field paths" too? So not just "rootelement", but "rootelement : linked-news : objects : title".

**Comment by nilshoerrmann** [comment]
Is this pull request still valid?

**Comment by ahwayakchih** [comment]
No, it was first try. Other one fixed the problem (while including parts of this pull :).

**Comment by nilshoerrmann** [comment]
Okay, we can move over to the issue tracker to discuss part that might still be missing in the current (and updated) implementation. Thanks for your work on this problem!

**Pull request closed without merging**
