### PR TITLE
Fixed items not showing up in XML (#111)

### PR DESCRIPTION
**Pull request by ahwayakchih**
Fixed items not showing up in XML (https://github.com/nilshoerrmann/subsectionmanager/issues/111) and made sorting a bit faster at the same time.

### CODE REVIEW

**Comment by nilshoerrmann** [comment]
Thanks for the additions - I'll check this out later this week.

**Comment by brendo** [comment]
I'll take a look ASAP too as our clients are constantly asking us about this bug

**Comment by nilshoerrmann** [comment]
Thanks, Brendan.

This is how it's done in the `tabs` branch - but the setup is different as the entries are prefetched in this branch so I only need to compare entry ids: https://github.com/nilshoerrmann/subsectionmanager/commit/162e3624ec3326c87be591a7e8036df1a8624bbd

**Comment by ahwayakchih** [comment]
I think that it would even be possible to drop additional SQL query, but sortorder would have to be stored in reversed order (or we would have to use more SQL functions).

**Pull request merged**
